//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShopWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_table = new HashSet<order_table>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int pdt_id { get; set; }
        public string pdt_name { get; set; }
        public string pdt_img { get; set; }
        public Nullable<int> pdt_price { get; set; }
        public string pdt_desc { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
        public Nullable<int> pdt_user_id_fk { get; set; }
    
        public virtual category category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_table> order_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
    }
}
